version: '3.9'
services:
  backend:
    build: ./backend
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      USE_SQLITE: "False"
      DATABASE_SSL_REQUIRE: "False"
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: tasktrackr
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
